language: cpp
compiler: gcc
sudo: require

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository ppa:sonkun/sfml-development -y
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-5  
  - sudo apt-get install libsfml-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - qmake
  - make
  - ./TowerBuilder &
  - sleep 10
  - sudo killall -9 TowerBuilder